# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=#020506

# Main text color
theme[main_fg]=#dde3e6

# Title color for boxes
theme[title]=#dde3e6

# Highlight color for keyboard shortcuts
theme[hi_fg]=#70e4ff

# Background color of selected item in processes box
theme[selected_bg]=#060a0a

# Foreground color of selected item in processes box
theme[selected_fg]=#70e4ff

# Color of inactive/disabled text
theme[inactive_fg]=#869397

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]=#ffcb9a

# Background color of the percentage meters
theme[meter_bg]=#869397

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]=#ffcb9a

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]=#72caf9
theme[mem_box]=#8af0f6
theme[net_box]=#abbef0
theme[proc_box]=#64c9ed

# Box divider line and small boxes line color
theme[div_line]=#3c494d

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]=#8af0f6
theme[temp_mid]=#d0f9f4
theme[temp_end]=#8ab5ff

# CPU graph colors (Teal -> Sapphire -> Lavender)
theme[cpu_start]=#a0ecf9
theme[cpu_mid]=#77d4ee
theme[cpu_end]=#8fd6f7

# Mem/Disk free meter (Mauve -> Lavender -> Blue)
theme[free_start]=#72caf9
theme[free_mid]=#8fd6f7
theme[free_end]=#64c9ed

# Mem/Disk cached meter (Sapphire -> Blue -> Lavender)
theme[cached_start]=#77d4ee
theme[cached_mid]=#64c9ed
theme[cached_end]=#8fd6f7

# Mem/Disk available meter (Peach -> Maroon -> Red)
theme[available_start]=#a9daac
theme[available_mid]=#abbef0
theme[available_end]=#8ab5ff

# Mem/Disk used meter (Green -> Teal -> Sky)
theme[used_start]=#8af0f6
theme[used_mid]=#a0ecf9
theme[used_end]=#96e7fb

# Download graph colors (Peach -> Maroon -> Red)
theme[download_start]=#a9daac
theme[download_mid]=#abbef0
theme[download_end]=#8ab5ff

# Upload graph colors (Green -> Teal -> Sky)
theme[upload_start]=#8af0f6
theme[upload_mid]=#a0ecf9
theme[upload_end]=#96e7fb

# Process box color gradient for threads, mem and cpu usage (Sapphire -> Lavender -> Mauve)
theme[process_start]=#77d4ee
theme[process_mid]=#8fd6f7
theme[process_end]=#72caf9
