-- Generated by nwg-displays on 2026-10-03 at 23:50:08. Do not edit manually.

hl.monitor({
    output = "Virtual-1",
    mode = "1280x800@74.99",
    position = "0x0",
    scale = 1.0,
    vrr = 0
})
